<a href="https://colab.research.google.com/github/adipta/First/blob/master/Principal%20Component%20Analyhsis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [3]:
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])

In [19]:
# Principal Component Analysis
from numpy import array
from sklearn.decomposition import PCA
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# create the PCA instance
pca = PCA(2)
# fit on data
pca.fit(A)
# access values and vectors
print(pca.components_)
print(pca.explained_variance_)
# transform data
B = pca.transform(A)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[8. 0.]
[[-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  2.22044605e-16]]


In [10]:
AT

array([[1, 3, 5],
       [2, 4, 6]])

In [14]:
m1=[mean(AT[0]), mean(AT[1])]

In [15]:
m1  

[3.0, 4.0]

In [17]:
[AT-m1]

ValueError: ignored